services:
  employeeevaluation360:
    image: ${DOCKER_REGISTRY-}employeeevaluation360
    build:
      context: .
      dockerfile: EmployeeEvaluation360/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=VietAn360_DB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
      - JWT__SigningKey=sdgfijjh3466iu345g87g08c24g7204gr803g30587ghh35807fg39074fvg80493745gf082b507807g807fgf
      - SmtpSettings__Password=avas qjum nlly akdo
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=YourCertPassword123
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./keys:/root/.aspnet/DataProtection-Keys
      - ${USERPROFILE}/.aspnet/https:/https:ro
    depends_on:
      sqlserver:
        condition: service_healthy
      sqlserver-init:
        condition: service_completed_successfully
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourStrong!Passw0rd' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

  sqlserver-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./ERD_DATN.sql:/ERD_DATN.sql
      - ./init-db.sh:/init-db.sh:ro
    command: ["bash", "/init-db.sh"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqlserver-data: