services:
  employeeevaluation360:
    image: ${DOCKER_REGISTRY-}employeeevaluation360
    build:
      context: .
      dockerfile: EmployeeEvaluation360/Dockerfile
    networks:
      - app-network
    depends_on:
      sqlserver:
        condition: service_healthy
      sqlserver-init:
        condition: service_completed_successfully

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourStrong!Passw0rd' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

  sqlserver-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./ERD_DATN.sql:/ERD_DATN.sql
      - ./init-db.sh:/init-db.sh:ro
    command: ["bash", "/init-db.sh"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqlserver-data: